# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache frontend npm directory
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn 
    - run: yarn test
    - run: yarn build
